project:
  type: website
  title: "submitted-202310-legrand"
  render:
    - computo_paper.qmd

number-sections: true
format:
  html:
    page-layout: article
    include-in-header: includes/pseudocode-header.html
    include-after-body: includes/pseudocode-footer.html
    date-format: long
    toc-title: >
      <a href="https://computo.sfds.asso.fr"><img style="width: 96px;" alt="Computo" src="https://computo.sfds.asso.fr/assets/img/logo_text_vertical.svg"/></a> <br/><br/>
      Contents
    toc: true
    theme: cosmo
    license: "CC BY"
    title-block-banner: "#034E79"
    title-block-banner-color: "#FFFFFF"
    hover-citations: true
    hover-footnotes: true
    highlight-style: github
    code-block-background: true
    code-block-border-left: "#034E79"
    code-tools:
      source: true
      toggle: false
      caption: "source"
    code-copy: true
    code-summary: "Show the code"
    code-fold: true
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    html-math-method: katex
    self-contained: true
  pdf:
    toc: true
    toc-title: Contents
    code-copy: true
    code-block-background: true
    pdf-engine: lualatex
    papersize: a4
    geometry: 
      - a4paper
      - textheight=24cm
      - textwidth=15.5cm
    fontfamily: libertinus
    fontsize: 11pt
    highlight-style: github
    monofont: Latin Modern Mono
    monofontoptions:
      - Scale=0.92
    include-in-header:
      - "partials/pdf/include-in-header.tex"
    template-partials:
      - "partials/pdf/_authors.tex"
      - "partials/pdf/before-body.tex"
crossref:
  sec-prefix: Section
  eq-prefix: Equation
  fig-prefix: Figure   
  tbl-prefix: Table
